version: '3.9'

services:

  django:
    build: ./Hello_World
    command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    volumes:
      - ./Hello_World:/project
      - static_data:/project/static
    expose:
      - 8000
        # environment:
        # - DATABASE_URL=postgres sql://django:django_QWErty@db:5432/django
        # - DEBUG=1
  db:
    container_name: postgres_cont
    image: postgresql:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django_QWErty
      - POSTGRES_DB=django
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data:
  static_data:
      
